title = "MyPortfolio"
baseURL = "https://AdachiKenta-0126.github.io/MyPortfolio/"
publishDir = "docs"
theme = "hugo-resume"
languageCode = "ja-jp"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false
canonifyurls = true

[params]
address = "Rollinsford, NH"
email = "shaluocilanzhe@gmail.com"
favicon = "/favicon.ico"
firstName = "Adachi"
lastName = "Kenta"
profileImage = "img/MyImage.png"
showEducation = false
showExperience = false
showOpenSource = false
showPublications = false
showQr = false
showSkills = false
showProjects = true

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://github.com/eddiewebb/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
